### ISSUE TITLE
Disabling the "UV Stretch" function

### ISSUE THREAD

**Issue by Calvin-rgb** [Oxicid/UniV#1]
![blender_0TjKhD9WM1](https://github.com/user-attachments/assets/147a2931-9b0a-4fa0-9fe6-a56b6c7b6c33)
Is it possible to add the ability to disable the UV Stretch backlight function?
It just sometimes interferes with work, and it's too far to get into the overlay settings, you could add hot cleavage or CheckBox in the addon panel
Thanks for the cool tool!

**Comment by Oxicid** [comment]
I was planning to add a similar option, but your request accelerated [that](https://github.com/Oxicid/UniV/commit/cde98bd862fd9274d5ddf2803f97dcceeb4779f9) idea.
