### ISSUE TITLE
Straight Tool Not Working Blender 4.2.1 LTS

### ISSUE THREAD

**Issue by WilliamDusk-Art** [Oxicid/UniV#2]
I am getting an error when trying to use the straight tool, it soo useful but lately it stopped working for me and just throws an error.
It happens with any mesh as far as I've seen
----------------------------------------------------------------------------------------------------------

Python: Traceback (most recent call last):
  File "...\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\univ\operators\straight.py", line 35, in execute
    for umesh in umeshes.loop():
  File "...AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\univ\utils\__init__.py", line 443, in loop
    area = [a for a in bpy.context.screen.areas if a.type == 'VIEW_3D'][0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Oxicid** [comment]
That bug was [fixed](https://github.com/Oxicid/UniV/commit/66c296e57d9c1979ceedcf758b28c25590758d0a)
